fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: b111689
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]
