function(FLAGS target)
	IF (WIN32)
	  target_compile_options(${target} PRIVATE /permissive- /W4 /W14640 /MP /Oi /arch:SSE2 /Gw)
	  target_compile_definitions(${target} PRIVATE _UNICODE UNICODE)
	  target_link_options(${target} PRIVATE /INCREMENTAL /LTCG)
	  IF (CMAKE_BUILD_TYPE EQUAL "Release")
		target_compile_options(${target} PRIVATE /LTCG)
	  ELSE()
		target_compile_options(${target} PRIVATE /RTC1)
	  ENDIF()
	ELSE()
	  target_compile_options(${target} PRIVATE -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic)
	ENDIF()
endfunction()