name: codacy-coverage-reporter

'on':
  - push
  - pull_request
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: cobertura.xml
      - name: Update coverage
        id: coverage_update
        run: 'curl -Os https://uploader.codecov.io/latest/linux/codecov'
      - name: Run coverage
        id: coverage
        run: 'sh ./codecov -t ${CODECOV_TOKEN}'