on:
  push:
    branches:
      - '**'

name: Discord Notification

jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: binotaliu/action-discord-notifier@v1
        with:
          message-title: New Commits Pushed
          webhook: ${{ secrets.DISCORD }}
